basket/urls.py
from django.urls import path

from . import views

app_name = "basket"

urlpatterns = [
    path("", views.basket_summary, name="basket_summary"),
    path("add/", views.basket_add, name="basket_add"),
    path("delete/", views.basket_delete, name="basket_delete"),
    path("update/", views.basket_update, name="basket_update"),
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='posts'),
    path('post/create', views.create_post, name='post-create'),
    path('post/edit/<int:id>/', views.edit_post, name='post-edit'),
    path('post/delete/<int:id>/', views.delete_post, name='post-delete'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("store.urls", namespace="store")),
    path("basket/", include("basket.urls", namespace="basket")),
    path('blog/', include('blog.urls')),
    path('account/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-blog-tag/personal_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),
]

django-blog/personal_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog.urls")),

]

store/urls.py
from django.urls import path

from . import views

app_name = "store"

urlpatterns = [
    path("", views.product_all, name="product_all"),
    path("<slug:slug>", views.product_detail, name="product_detail"),
    path("product/<slug:category_slug>/", views.category_list, name="category_list"),
    path("about/", views.about, name="about"),
]

templates/about.html
{% extends 'base.html' %}

{% block content %}

<div class="container px-4 py-5">
    <h1 class="pb-2 border-bottom">We Take Care Of Pets, Like Pets Take Care Of You</h1>

    <div class="row row-cols-1 row-cols-md-2 align-items-md-center g-5 py-5">
      <div class="col d-flex flex-column align-items-start gap-2">
        <h2 class="fw-bold text-body-emphasis">Your Pet's Health</h2>
        <p class="text-body-secondary">
			Pets are always there for us – so it’s only fair that we’re always there for them, too.  
			That’s why our team of pet-lovers, scientists, vets, and more, have dedicated over 70 years to advancing pet health.  
			Our products are so trusted and effective, they’re in almost every vet practice in the country.
		</p>
      </div>

      <div class="col">
        <div class="row row-cols-1">
			<img src="https://images.contentstack.io/v3/assets/blt6f84e20c72a89efa/blt499d2c1c50cb0e42/62fc03db563f757dc2b32f4c/03-img-innovator-about.jpg" class="img-fluid" alt="...">
        </div>
      </div>
    </div>

	<div class="row row-cols-1 row-cols-md-2 align-items-md-center g-5 py-5">
		<div class="col d-flex flex-column align-items-start gap-2">
		  <h2 class="fw-bold text-body-emphasis">Supporting You</h2>
		  <p class="text-body-secondary">
			While we continue to seek out new and better ways to help pets live long, healthy lives, we think it’s equally important that you’ve got the tools you need.
		  </p>
		</div>
  
		<div class="col">
		  <div class="row row-cols-1">
			  <img src="https://images.contentstack.io/v3/assets/blt6f84e20c72a89efa/blt851946be01365ee9/62fc03de99ceba04394822cc/04-img-guidance-about.jpg" class="img-fluid" alt="...">
		  </div>
		</div>
	  </div>


	  <div class="row row-cols-1 row-cols-md-2 align-items-md-center g-5 py-5">
		<div class="col d-flex flex-column align-items-start gap-2">
		  <h2 class="fw-bold text-body-emphasis">The Pet Community</h2>
		  <h2 class="fw-bold text-body-emphasis">Helping Pets and Those That Care for Them</h2>
		  <p class="text-body-secondary">
			Pets give us so much. 
			That’s why we’re committed not only to their health, but to those that love and care for them. We partner and support a variety of initiatives dedicated to the greater pet community; 
			from the shelters that help them find homes, to the vets that dedicate themselves to their wellbeing, to the parents that make them part of a loving family. 
		  </p>
		</div>
  
		<div class="col">
		  <div class="row row-cols-1">
			  <img src="https://images.contentstack.io/v3/assets/blt6f84e20c72a89efa/blt260bea5c2aba01fb/62fc03e573cb7a70443e6ed6/06-img-community-about.jpg" class="img-fluid" alt="...">
		  </div>
		</div>
	  </div>
  </div>

{% endblock content%}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}Pet Care Store{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">
                    <img src="https://raw.githubusercontent.com/vtcstudent2021/DjangoTest/test/StoreDjangoProject/stroe/static/image/Logo.png" alt="Logo" width="60" height="60" >
                    Pet Care Store
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-grid gap-2 d-md-block" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">Products</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="{% url "store:product_all" %}">All</a></li>
                                {% for c in categories %}
                                <li {% if category.slug == c.slug %}class="selected" {% endif %}>
                                    <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                                </li>
                                {% endfor %}
                            </ul>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="/blog/">Blog</a></li>
                        <li class="nav-item"><a class="nav-link" href="/about/">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="/">Store Address</a></li>
                        <li class="nav-item"><a class="nav-link" href="/">AI Chat Bot</a></li>
                    </ul>
                    <a type="button" role="button" class="btn btn-outline-success" href="{% url "basket:basket_summary" %}">
                        Cart
                        {% with total_qty=basket|length %}
                            <div id="basket-qty" class="d-inline-flex">
                                {% if total_qty > 0 %}
                                    {{ total_qty }}
                                {% else %} 
                                    0
                                {% endif %} 
                            </div>
                        {% endwith %}   
                    </a>

                    {%if request.user.is_authenticated %}
                        <span class="btn btn-outline-success">Hi {{ request.user.username | title }}</span>
                        <a type="button" role="button" class="btn btn-outline-success" href="{% url 'logout' %}">Logout</a>
                    {%else%}
                        <a type="button" role="button" class="btn btn-outline-success" href="{% url 'login' %}">Login</a>
                        <a type="button" role="button" class="btn btn-outline-success" href="{% url 'register' %}">Register</a>
                    {%endif%}


                </div>

            </div>
        </nav>
    </header>
    {% block content %} {% endblock %}

    <footer class="py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
          <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Products</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Blog</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Store Address</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">AI Chat Bot</a></li>
        </ul>
        <p class="text-center text-body-secondary">© 2024 Company, Inc</p>
      </footer>

</body>


</html>

templates/blogbase.html
{%load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script src="{% static 'js/app.js' %}" defer></script>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </head>
  <body>

	<div class="container">
		<header class="border-bottom lh-1 py-3">
		  <div class="">
			{%if request.user.is_authenticated %}
			<a href="{% url 'posts' %}">My Posts</a>
			<a href="{% url 'post-create' %}">New Post</a>
			<span>Hi {{ request.user.username | title }}</span>
			<a href="{% url 'logout' %}">Logout</a>
		{%else%}
			<a href="{% url 'login' %}">Login</a>
			<a href="{% url 'register' %}">Register</a>
		{%endif%}
		  </div>
		</header>
		<div class="nav-scroller py-1 mb-3 border-bottom">
		  <nav class="nav nav-underline">
			<a class="nav-item nav-link link-body-emphasis" href="/">Home</a>
			<a class="nav-item nav-link link-body-emphasis" href="#">World</a>

		  </nav>
		</div>
		{% if messages %}
		<div class="messages">
		{% for message in messages %}
			<div class="alert {% if message.tags %}alert-{{ message.tags }}"{% endif %}>
				{{ message }}
			</div>
		{% endfor %}
		</div>
		{% endif %}
		{%block content%} 
	    {%endblock content%}
	  </div>

	  <footer class="py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
          <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Products</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Blog</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Store Address</a></li>
          <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">AI Chat Bot</a></li>
        </ul>
        <p class="text-center text-body-secondary">© 2024 Company, Inc</p>
      </footer>
	
  </body>
</html>

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}
<main>

  <section class="py-5 text-center">
    <img src="https://raw.githubusercontent.com/vtcstudent2021/DjangoTest/test/StoreDjangoProject/stroe/static/image/banner.jpg" class="img-fluid" alt="...">
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="pb-3 h5">Most Popular Items</div>
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
        {% for product in products %}
        <div class="col">
          <div class="card shadow-sm">
            <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
            <div class="card-body">
              <p class="card-text h5">
                <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
              </p>
              <div class="stars">
                <span class="star">★</span>
                <span class="star">★</span>
                <span class="star">★</span>
                <span class="star">★</span>
                <span class="star">★</span>
              </div>
              <span class="h4 fw-bold">HK${{ product.price }}</span>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      <hr class="my-4">
    </div>

  </div>

</main>
{% endblock %}